# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, task4]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  solve:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Build
      run: |
        cd task4 
        mkdir 3rdparty
        mkdir install_folder
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ..
        MAIN_DIR=$(pwd)
        echo ${MAIN_DIR}
        mkdir build
        cd build
        cmake -DGOOGLE_TEST_DIR=googletest -DORIGIN=$(pwd) -DCMAKE_INSTALL_PREFIX=$MAIN_DIR/install_folder ..
        make
        make install

#     - name: Test
#       uses: akhtyamovpavel/ActionGtestReport@v0.0.9
#       with: 
#         exec-path: /home/runner/work/Tp/Tp/task4/bin/CTestExe
#         run: |
        
        
#     - name: UploadArtifacts
#       run: |
#         echo axaxaxaxaxax
            
    
